# Generated by Django 3.1.13 on 2022-11-17 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather_api', '0003_person'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Person',
            new_name='Suscribe',
        ),
    ]
